name: clean-code-ml
dependencies:
  - python=3.6
  - jupyter=1.0.0
  - matplotlib=3.0.2
  - numpy=1.16.4
  - pandas=0.23.4
  - scikit-learn=0.21.2
  - seaborn=0.9.0
  - pip=19.1.1
  - pip:
    - autopep8==1.4.4
    - nose==1.3.7
    - nose-watch==0.9.2
    - rednose==1.3.0
